// pnpm --filter @qryvox/backend api:docs — local API explorer: Swagger UI at http://localhost:8788/docs over the
// real backend (same database, model and guards as `pnpm dev`, read from ../.env). A development tool only:
// nothing deployed imports it, so production never serves /docs.
//
// The OpenAPI document is generated from the request/response schemas in @qryvox/shared, so it cannot drift
// from the contract. A new endpoint must be added to `paths` below, with its text in both languages in `TEXT`.
//
// The page switches between English and Traditional Chinese. That covers everything we write (descriptions,
// summaries, status codes); Swagger UI's own labels ("Try it out", "Execute") have no translation mechanism
// and stay in English.
import { serve } from "@hono/node-server";
import {
  AppendResponse,
  ErrorResponse,
  EVENT_PAGE_LIMIT,
  EventPage,
  EventPayloadResponse,
  IngestDocumentRequest,
  OpenCaseRequest,
  OpenCaseResponse,
  RunStepRequest,
  StepFailure,
  StepResult,
  VerifyResponse,
} from "@qryvox/shared";
import { Hono } from "hono";
import { z } from "zod";
import { createApp } from "../src/app";
import { assertAppendOnly } from "../src/db/append-only";
import { openDatabase, runMigrations } from "../src/db/client";
import { env } from "../src/env";
import { createLlm } from "../src/llm";

const port = Number(process.env.DOCS_PORT ?? 8788);
const origin = `http://localhost:${port}`;

const LANGS = ["en", "zh-Hant"] as const;
type Lang = (typeof LANGS)[number];

const TEXT = {
  en: {
    title: "Qryvox backend",
    description:
      "Append-only, hash-chained event log and the four analysis steps. Requests and responses are the zod " +
      "contracts in @qryvox/shared. event_id and step_run_id are generated by the caller, so a retry reuses them.",
    unknownCase: "Unknown case",
    invalidBody: "Invalid body",
    health: "Health, with the shared event vocabulary",
    healthOk: "Up; eventTypes proves @qryvox/shared resolved",
    openCase: "Open a case",
    openCaseDesc: "Appends one case.opened. The case id is the event_id; a retry returns the same case.",
    opened: "Opened",
    ingest: "Ingest a document",
    ingestDesc: "Appends document.ingested with the per-page text extracted by pdf.js. Idempotent by event_id.",
    ingested: "Ingested",
    ingestInvalid: "Invalid body, or page_count differs from the pages sent",
    step: "Run one analysis step",
    stepDesc:
      "extract (input_run_id null) → decompose → contradictions → findings, each consuming the previous " +
      "completed run. A completed step_run_id returns its stored result without calling the model.",
    stepOk: "Completed, now or earlier",
    stepPrecondition: "Cannot run yet: no documents, or input_run_id is not a completed run of the previous step",
    stepSchema: "Model output failed its schema or grounding; step.failed appended",
    rateLimited: "Rate limited; see Retry-After",
    stepUnreachable: "Model unreachable; step.failed appended",
    noModel: "No model configured",
    events: "List events (slim), paged by seq",
    eventsOk: "Events with seq > after",
    payload: "One event's full payload, heavy fields included",
    payloadOk: "Full payload",
    noEvent: "No such event",
    verify: "Re-hash the case's chain",
    verifyOk: "Verdict and latest hash",
  },
  "zh-Hant": {
    title: "Qryvox 後端",
    description:
      "只能追加、以雜湊串鏈的事件日誌，以及四個分析步驟。請求與回應皆為 @qryvox/shared 中的 zod 契約。" +
      "event_id 與 step_run_id 由呼叫端產生，重試時沿用同一個值。",
    unknownCase: "找不到此案件",
    invalidBody: "請求內容不正確",
    health: "健康檢查，並回傳共用的事件類型清單",
    healthOk: "服務正常；eventTypes 證明 @qryvox/shared 已正確載入",
    openCase: "開啟案件",
    openCaseDesc: "追加一筆 case.opened。案件 ID 即為 event_id；重試會回傳同一個案件。",
    opened: "已開啟",
    ingest: "匯入文件",
    ingestDesc: "追加一筆 document.ingested，內含 pdf.js 逐頁擷取的文字。以 event_id 確保冪等。",
    ingested: "已匯入",
    ingestInvalid: "請求內容不正確，或 page_count 與送出的頁數不符",
    step: "執行一個分析步驟",
    stepDesc:
      "extract（input_run_id 為 null）→ decompose → contradictions → findings，每一步都讀取上一步已完成的結果。" +
      "已完成的 step_run_id 會直接回傳儲存的結果，不會呼叫模型。",
    stepOk: "已完成（本次或先前）",
    stepPrecondition: "目前無法執行：尚未匯入文件，或 input_run_id 不是上一步已完成的執行",
    stepSchema: "模型輸出未通過結構或原文比對檢查；已追加 step.failed",
    rateLimited: "超過頻率限制；請見 Retry-After",
    stepUnreachable: "無法連線到模型；已追加 step.failed",
    noModel: "尚未設定模型",
    events: "列出事件（精簡版），依 seq 分頁",
    eventsOk: "seq 大於 after 的事件",
    payload: "單一事件的完整內容，包含大型欄位",
    payloadOk: "完整內容",
    noEvent: "找不到此事件",
    verify: "重新計算案件的雜湊鏈",
    verifyOk: "驗證結果與最新雜湊值",
  },
} satisfies Record<Lang, Record<string, string>>;

const schemas = {
  OpenCaseRequest,
  OpenCaseResponse,
  IngestDocumentRequest,
  AppendResponse,
  EventPage,
  EventPayloadResponse,
  VerifyResponse,
  RunStepRequest,
  StepResult,
  StepFailure,
  ErrorResponse,
};

// OpenAPI 3.1 takes JSON Schema 2020-12 as is, minus the $schema marker.
function component(schema: z.ZodType) {
  const json: Record<string, unknown> = z.toJSONSchema(schema, { unrepresentable: "any" });
  delete json.$schema;
  return json;
}

const components = { schemas: Object.fromEntries(Object.entries(schemas).map(([name, s]) => [name, component(s)])) };

function openapi(lang: Lang) {
  const t = TEXT[lang];
  const ref = (name: keyof typeof schemas) => ({ $ref: `#/components/schemas/${name}` });
  const body = (name: keyof typeof schemas) => ({ required: true, content: { "application/json": { schema: ref(name) } } });
  const json = (name: keyof typeof schemas, description: string) => ({
    description,
    content: { "application/json": { schema: ref(name) } },
  });
  const error = (description: string) => json("ErrorResponse", description);
  const caseId = { name: "caseId", in: "path", required: true, schema: { type: "string" } };

  return {
    openapi: "3.1.0",
    info: { title: t.title, version: "stage-1", description: t.description },
    servers: [{ url: origin }],
    paths: {
      "/health": {
        get: { summary: t.health, responses: { 200: { description: t.healthOk } } },
      },
      "/cases": {
        post: {
          summary: t.openCase,
          description: t.openCaseDesc,
          requestBody: body("OpenCaseRequest"),
          responses: { 201: json("OpenCaseResponse", t.opened), 400: error(t.invalidBody) },
        },
      },
      "/cases/{caseId}/documents": {
        post: {
          summary: t.ingest,
          description: t.ingestDesc,
          parameters: [caseId],
          requestBody: body("IngestDocumentRequest"),
          responses: {
            201: json("AppendResponse", t.ingested),
            400: error(t.ingestInvalid),
            404: error(t.unknownCase),
          },
        },
      },
      "/cases/{caseId}/steps": {
        post: {
          summary: t.step,
          description: t.stepDesc,
          parameters: [caseId],
          requestBody: body("RunStepRequest"),
          responses: {
            200: json("StepResult", t.stepOk),
            404: error(t.unknownCase),
            409: error(t.stepPrecondition),
            422: json("StepFailure", t.stepSchema),
            429: error(t.rateLimited),
            502: json("StepFailure", t.stepUnreachable),
            503: error(t.noModel),
          },
        },
      },
      "/cases/{caseId}/events": {
        get: {
          summary: t.events,
          parameters: [
            caseId,
            { name: "after", in: "query", schema: { type: "integer", minimum: 0, default: 0 } },
            { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: EVENT_PAGE_LIMIT } },
          ],
          responses: { 200: json("EventPage", t.eventsOk), 404: error(t.unknownCase) },
        },
      },
      "/cases/{caseId}/events/{seq}/payload": {
        get: {
          summary: t.payload,
          parameters: [caseId, { name: "seq", in: "path", required: true, schema: { type: "integer", minimum: 1 } }],
          responses: { 200: json("EventPayloadResponse", t.payloadOk), 404: error(t.noEvent) },
        },
      },
      "/cases/{caseId}/verify": {
        get: {
          summary: t.verify,
          parameters: [caseId],
          responses: { 200: json("VerifyResponse", t.verifyOk), 404: error(t.unknownCase) },
        },
      },
    },
    components,
  };
}

// The switch remembers the choice in localStorage (falling back silently where storage is blocked) and keeps
// it in the URL, so a link opens in the same language.
const page = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Qryvox API</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css">
  <style>
    body { margin: 0; background: #fff; }
    .lang { display: flex; justify-content: flex-end; gap: 4px; padding: 12px 20px 0; font-family: system-ui, sans-serif; }
    .lang button { border: 1px solid #c4c4c4; background: #fff; color: #3b4151; border-radius: 4px; padding: 6px 12px; font-size: 14px; cursor: pointer; }
    .lang button[aria-pressed="true"] { background: #3b4151; border-color: #3b4151; color: #fff; }
  </style>
</head>
<body>
  <nav class="lang" aria-label="Language">
    <button type="button" data-lang="en">English</button>
    <button type="button" data-lang="zh-Hant">繁體中文</button>
  </nav>
  <div id="ui"></div>
  <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    const LANGS = ${JSON.stringify(LANGS)};
    function stored() { try { return localStorage.getItem("qryvox-docs-lang"); } catch { return null; } }
    function remember(lang) { try { localStorage.setItem("qryvox-docs-lang", lang); } catch {} }
    function show(lang) {
      document.documentElement.lang = lang;
      for (const b of document.querySelectorAll(".lang button")) b.setAttribute("aria-pressed", String(b.dataset.lang === lang));
      const url = new URL(location.href);
      url.searchParams.set("lang", lang);
      history.replaceState(null, "", url);
      remember(lang);
      document.getElementById("ui").replaceChildren();
      SwaggerUIBundle({ url: "/openapi.json?lang=" + lang, dom_id: "#ui" });
    }
    for (const b of document.querySelectorAll(".lang button")) b.addEventListener("click", () => show(b.dataset.lang));
    const wanted = new URLSearchParams(location.search).get("lang") || stored();
    show(LANGS.includes(wanted) ? wanted : "en");
  </script>
</body>
</html>`;

const database = openDatabase(env.databaseUrl, env.databaseAuthToken);
await runMigrations(database.db);
await assertAppendOnly(database.client);
const llm = env.llm ? createLlm(env.llm) : null;
// The explorer's own origin is allowed here only; the deployed backend's allow-list is unchanged.
const api = createApp({ ...database, llm, guards: { ...env.guards, allowedOrigins: [...env.guards.allowedOrigins, origin] } });

const explorer = new Hono();
explorer.get("/docs", (c) => c.html(page));
explorer.get("/openapi.json", (c) => {
  const lang = c.req.query("lang");
  return c.json(openapi(LANGS.includes(lang as Lang) ? (lang as Lang) : "en"));
});
explorer.route("/", api);

serve({ fetch: explorer.fetch, port }, () => {
  console.log(`API explorer: ${origin}/docs (${env.databaseUrl})`);
  console.log(llm ? `model: ${llm.model} at ${env.llm?.baseUrl}` : "model: not configured (LLM_BASE_URL / LLM_MODEL)");
});
