// pnpm --filter @qryvox/backend api:docs — local API explorer: Swagger UI at http://localhost:8788/docs over the
// real backend (same database, model and guards as `pnpm dev`, read from ../.env). A development tool only:
// nothing deployed imports it, so production never serves /docs.
//
// The OpenAPI document is generated from the request/response schemas in @qryvox/shared, so it cannot drift
// from the contract. A new endpoint must be added to `paths` below, with its text in both languages in `TEXT`.
//
// The page switches between English and Traditional Chinese. That covers everything we write (descriptions,
// summaries, status codes); Swagger UI's own labels ("Try it out", "Execute") have no translation mechanism
// and stay in English.
import { serve } from "@hono/node-server";
import {
  AppendResponse,
  CardOperationRequest,
  CardOperationResponse,
  ChangeDispositionRequest,
  ClientCasesResponse,
  ClientQueueResponse,
  ClientListResponse,
  DecideAdviceRequest,
  DecideListRequest,
  DraftAdviceRequest,
  ErrorResponse,
  EVENT_PAGE_LIMIT,
  EventPage,
  EventPayloadResponse,
  IngestDocumentRequest,
  API_TOKEN_HEADER,
  OpenCaseRequest,
  OpenCaseResponse,
  RecordClientListRequest,
  RecordProfileRequest,
  RecordReadingRequest,
  RunStepRequest,
  StepFailure,
  StepResult,
  VerifyResponse,
} from "@qryvox/shared";
import { Hono } from "hono";
import { z } from "zod";
import { createApp } from "../src/app";
import { assertAppendOnly } from "../src/db/append-only";
import { openDatabase, runMigrations } from "../src/db/client";
import { env } from "../src/env";
import { createLlm } from "../src/llm";

const port = Number(process.env.DOCS_PORT ?? 8788);
const origin = `http://localhost:${port}`;

const LANGS = ["en", "zh-Hant"] as const;
type Lang = (typeof LANGS)[number];

const TEXT = {
  en: {
    title: "Qryvox backend",
    description:
      "Append-only, hash-chained event log and the four analysis steps. Requests and responses are the zod " +
      "contracts in @qryvox/shared. event_id and step_run_id are generated by the caller, so a retry reuses them.",
    unknownCase: "Unknown case",
    invalidBody: "Invalid body",
    health: "Health, with the shared event vocabulary",
    healthOk: "Up; eventTypes proves @qryvox/shared resolved",
    openCase: "Open a case",
    openCaseDesc: "Appends one case.opened. The case id is the event_id; a retry returns the same case.",
    opened: "Opened",
    ingest: "Ingest a document",
    ingestDesc: "Appends document.ingested with the per-page text extracted by pdf.js. Idempotent by event_id.",
    ingested: "Ingested",
    ingestInvalid: "Invalid body, or page_count differs from the pages sent",
    step: "Run one analysis step",
    stepDesc:
      "extract (input_run_id null) → decompose → contradictions → findings, each consuming the previous " +
      "completed run. A completed step_run_id returns its stored result without calling the model. " +
      "seed (extract and contradictions only) makes a find-similar run: a citation whose quote must appear on its " +
      "page; the run returns only statements or issues about that passage's subject, and no step consumes it, so " +
      "the findings on the board never change. " +
      "parse (input_run_id null) needs intent, the analyst's own words (up to 500 characters, any language), and " +
      "returns them as intent chips: a category, a document kind and a step from their fixed lists, or [] when " +
      "the words name none. intent is refused on every other step. " +
      "rationale (input_run_id: a completed findings run still on the board) is optional: one model call writes a " +
      "plain-language sentence on why each of that run's findings matters, as {rationales: [{finding_id, text}]}. " +
      "Whatever a sentence quotes must be verbatim in its finding's citation or counterpart, and every number it " +
      "states must be in them; a sentence that does not hold is dropped, and the run fails only if none holds.",
    stepOk: "Completed, now or earlier",
    stepInvalid:
      "Invalid body: intent missing on parse or sent on another step, a seed on a step that takes none, or a seed " +
      "quote not found on its cited page",
    stepPrecondition: "Cannot run yet: no documents, or input_run_id is not a completed run of the previous step",
    stepSchema: "Model output failed its schema or grounding; step.failed appended",
    rateLimited: "Rate limited; see Retry-After",
    apiToken: "API token (API_TOKEN); needed only when the backend sets one",
    noApiToken: "API token missing or wrong",
    stepUnreachable: "Model unreachable; step.failed appended",
    noModel: "No model configured",
    events: "List events (slim), paged by seq",
    eventsOk: "Events with seq > after",
    dispose: "Approve or dismiss a finding",
    disposeDesc:
      "Appends disposition.changed, attributed to the analyst. Only a person decides: no step ever approves or " +
      "dismisses. Deciding again replaces the decision on the board; both stay in the log. Idempotent by event_id.",
    disposed: "Recorded",
    disposeInvalid: "Invalid body; disposition must be approved or dismissed",
    noFinding: "Unknown case, or the case never produced this finding",
    superseded: "The finding was superseded by a later findings run and is off the board",
    card: "Record a card operation on the canvas",
    cardDesc:
      "Appends one card event, attributed to the analyst: card.docked (into a plan slot), card.undocked, card.pinned " +
      "(at a world position), card.unpinned, card.discarded, card.restored, or card.similar_requested (step_kind " +
      "extract, whichever card it is pressed from; any seedable step is admitted, so contradictions can still " +
      "be seeded; the seeded run itself is a separate call to /steps). Nothing touches a finding: discarding a " +
      "finding card is not dismissing it. Idempotent by event_id. Answers with the event appended.",
    cardRecorded: "Recorded; the card event as appended",
    cardInvalid: "Invalid body: not a card event, a malformed card id, or find similar naming a step that takes no seed",
    cardRefused:
      "The case has no such card (a finding not on the board, or a passage no active finding cites and no completed " +
      "find-similar run returned), a dock into a slot of another category, or the event_id used by another event",
    profile: "Record a client's profile",
    profileDesc:
      "Appends client.profiled: a new version of the client's answers, under a pseudonymous id (never a name). " +
      "Advice drafted on the previous version is superseded in the same transaction. Idempotent by event_id.",
    profiled: "Recorded",
    profileInvalid: "Invalid body; client_id must be a pseudonymous id and every answer one of the allowed values",
    draftAdvice: "Draft advice for a client",
    draftAdviceDesc:
      "Applies the suitability rules (rules@1) to the client's latest profile and the latest completed attributes " +
      "run, and appends advice.drafted; the advice's id is this event_id. No model is called. Advice still in play " +
      "on an older attributes run is superseded. Idempotent by event_id.",
    drafted: "Drafted",
    adviceRefused:
      "No profile for this client, the pack not yet verified (no completed findings run), no completed attributes " +
      "run, or advice already drafted on these same inputs",
    decideAdvice: "Approve or reject drafted advice",
    decideAdviceDesc:
      "Appends advice.decided, attributed to the adviser. A client only ever sees approved advice still in play. " +
      "Idempotent by event_id: a retry of a recorded decision returns it even after the advice was superseded.",
    noAdvice: "Unknown case, or the case has no such advice",
    adviceSuperseded: "The advice was superseded by a newer profile or attributes run",
    reading: "Record the depth a client chose",
    readingDesc:
      "Appends client.read, with the client's pseudonymous id as the actor. Sent only once the client has switched on " +
      "sharing on their own page. Three choices in a row of another depth suggest the adviser asks again; nothing " +
      "changes a profile by itself.",
    noClient: "Unknown case, or the case has no such client",
    clientList: "Record a client's answers across every verified product",
    clientListDesc:
      "A client's answers, given once on /start: appends client.profiled in every verified product's case and drafts " +
      "advice against each (rules@1; no model is called). event_id is the browser's: every event the call appends takes " +
      "an id derived from it and the case, so a retry after a partial failure finishes the rest and appends nothing twice. " +
      "Answers with the client's list: one product per case, with its advice id.",
    clientListRecorded: "Recorded and drafted; the client's list",
    clientListNoProduct:
      "No product has been verified yet: an analyst must finish a review, including reading the product's facts, before clients can be checked",
    clientCases: "The cases that hold a client's answers",
    clientQueue: "The adviser's queue of clients",
    clientQueueDesc: "Read-only. Every client with advice in play, oldest answers first: whether they are vulnerable, and each case holding their advice with its verdict and decision (null while it awaits the adviser).",
    clientQueueOk: "The clients with advice in play (empty when there are none)",
    clientCasesDesc: "Where the client's list is read from: the ids of the cases with a client.profiled for this pseudonymous id.",
    clientCasesOk: "The case ids (empty when the client is unknown)",
    decideList: "Approve or reject a client's whole list",
    decideListDesc:
      "Appends advice.decided, attributed to the adviser, on every advice of the client's in play, in one decision. " +
      "A rejection needs its reason. pick_case_id marks one suitable product as the adviser's pick, on approval only; " +
      "the client then sees it as Recommended. Idempotent by event_id: every event takes an id derived from it and the case.",
    decideListOk: "Decided; the products it covered",
    decideListRefused:
      "No advice in play to decide, a pick on a rejection, a pick not on the client's list, or a pick the rules do not find suitable",
    payload: "One event's full payload, heavy fields included",
    payloadOk: "Full payload",
    noEvent: "No such event",
    verify: "Re-hash the case's chain",
    verifyOk: "Verdict and latest hash",
  },
  "zh-Hant": {
    title: "Qryvox 後端",
    description:
      "只能追加、以雜湊串鏈的事件日誌，以及四個分析步驟。請求與回應皆為 @qryvox/shared 中的 zod 契約。" +
      "event_id 與 step_run_id 由呼叫端產生，重試時沿用同一個值。",
    unknownCase: "找不到此案件",
    invalidBody: "請求內容不正確",
    health: "健康檢查，並回傳共用的事件類型清單",
    healthOk: "服務正常；eventTypes 證明 @qryvox/shared 已正確載入",
    openCase: "開啟案件",
    openCaseDesc: "追加一筆 case.opened。案件 ID 即為 event_id；重試會回傳同一個案件。",
    opened: "已開啟",
    ingest: "匯入文件",
    ingestDesc: "追加一筆 document.ingested，內含 pdf.js 逐頁擷取的文字。以 event_id 確保冪等。",
    ingested: "已匯入",
    ingestInvalid: "請求內容不正確，或 page_count 與送出的頁數不符",
    step: "執行一個分析步驟",
    stepDesc:
      "extract（input_run_id 為 null）→ decompose → contradictions → findings，每一步都讀取上一步已完成的結果。" +
      "已完成的 step_run_id 會直接回傳儲存的結果，不會呼叫模型。" +
      "seed（僅限 extract 與 contradictions）代表「找相似」執行：一筆引文，其引文內容必須出現在所標示的頁面上；" +
      "此執行只回傳與該段落同一主題的陳述或問題，且不會被任何步驟讀取，因此看板上的發現不會改變。" +
      "parse（input_run_id 為 null）需要 intent，即分析師自己輸入的文字（最多 500 字，任何語言皆可），" +
      "並將其轉為意圖標籤：各自從固定清單中選出的類別、文件種類與步驟；文字未提及任何一項時回傳 []。其他步驟不接受 intent。" +
      "rationale（input_run_id 為仍在看板上的已完成 findings 執行）為選用步驟：以一次模型呼叫，為該次執行的每一筆發現" +
      "寫一句白話說明其對投資者的影響，格式為 {rationales: [{finding_id, text}]}。句中引用的文字必須與該發現的引文或對照引文" +
      "完全一致，所提及的數字也必須出現在其中；不符合的句子會被捨棄，只有全部都不符合時，執行才會失敗。",
    stepOk: "已完成（本次或先前）",
    stepInvalid:
      "請求內容不正確：parse 缺少 intent 或其他步驟送出 intent、對不接受 seed 的步驟送出 seed，或 seed 的引文不在所標示的頁面上",
    stepPrecondition: "目前無法執行：尚未匯入文件，或 input_run_id 不是上一步已完成的執行",
    stepSchema: "模型輸出未通過結構或原文比對檢查；已追加 step.failed",
    rateLimited: "超過頻率限制；請見 Retry-After",
    apiToken: "API token（API_TOKEN）；backend 有設定時才需要",
    noApiToken: "API token 缺少或錯誤",
    stepUnreachable: "無法連線到模型；已追加 step.failed",
    noModel: "尚未設定模型",
    events: "列出事件（精簡版），依 seq 分頁",
    eventsOk: "seq 大於 after 的事件",
    dispose: "核准或駁回一筆發現",
    disposeDesc:
      "追加一筆 disposition.changed，記錄為分析師所做。只有人能做決定：任何步驟都不會自動核准或駁回。" +
      "再次決定會取代看板上的結果，兩筆都保留在日誌中。以 event_id 確保冪等。",
    disposed: "已記錄",
    disposeInvalid: "請求內容不正確；disposition 必須是 approved 或 dismissed",
    noFinding: "找不到此案件，或此案件沒有這筆發現",
    superseded: "這筆發現已被之後的 findings 執行取代，不在看板上",
    card: "記錄畫布上的卡片操作",
    cardDesc:
      "追加一筆卡片事件，記錄為分析師所做：card.docked（放入計畫區的某一格）、card.undocked、card.pinned（固定在畫布座標）、" +
      "card.unpinned、card.discarded、card.restored，或 card.similar_requested（不論從哪一種卡片按出，step_kind 都是 " +
      "extract；任何可接受種子的步驟都允許，因此仍可帶種子執行 contradictions；帶種子的重新執行本身另外呼叫 /steps）。" +
      "不會改動任何發現：丟棄發現卡片不等於駁回該發現。以 event_id 確保冪等。回傳所追加的事件。",
    cardRecorded: "已記錄；回傳所追加的卡片事件",
    cardInvalid: "請求內容不正確：不是卡片事件、卡片 ID 格式錯誤，或「找相似」指定了不接受種子的步驟",
    cardRefused:
      "此案件沒有這張卡片（發現不在看板上，或摘錄既未被任何有效發現引用、也不是已完成的「找相似」執行所回傳），" +
      "放入其他類別的格子，或 event_id 已被其他事件使用",
    profile: "記錄客戶檔案",
    profileDesc:
      "追加一筆 client.profiled：客戶答案的新版本，使用化名 ID（不可填姓名）。" +
      "依舊版本起草的建議會在同一筆交易中被取代。以 event_id 確保冪等。",
    profiled: "已記錄",
    profileInvalid: "請求內容不正確；client_id 必須是化名 ID，每個答案都必須是允許的選項",
    draftAdvice: "為客戶起草建議",
    draftAdviceDesc:
      "以適合度規則（rules@1）比對客戶最新的檔案與最新完成的 attributes 執行，並追加 advice.drafted；" +
      "建議的 ID 就是這個 event_id。不會呼叫模型。仍有效、但依舊 attributes 執行起草的建議會被取代。以 event_id 確保冪等。",
    drafted: "已起草",
    adviceRefused: "此客戶沒有檔案、文件包尚未核實（沒有完成的 findings 執行）、沒有完成的 attributes 執行，或已依相同輸入起草過",
    decideAdvice: "核准或退回建議草稿",
    decideAdviceDesc:
      "追加一筆 advice.decided，記錄為顧問所做。客戶只會看到已核准且仍有效的建議。" +
      "以 event_id 確保冪等：已記錄的決定重送時會回傳原結果，即使建議之後已被取代。",
    noAdvice: "找不到此案件，或此案件沒有這筆建議",
    adviceSuperseded: "這筆建議已被較新的客戶檔案或 attributes 執行取代",
    reading: "記錄客戶選擇的說明深度",
    readingDesc:
      "追加一筆 client.read，以客戶的化名 ID 為行動者。只有客戶在自己的頁面開啟分享後才會送出。" +
      "連續三次選擇另一種深度時，會提示顧問重新詢問；系統不會自行修改客戶檔案。",
    noClient: "找不到此案件，或此案件沒有這位客戶",
    clientList: "記錄客戶對所有已核實產品的答案",
    clientListDesc:
      "客戶在 /start 一次填寫的答案：在每個已核實產品的案件中追加 client.profiled，並依各案件起草建議" +
      "（rules@1；不會呼叫模型）。event_id 由瀏覽器產生：這次呼叫追加的每一筆事件，其 ID 都由它與案件推導而來，" +
      "因此部分失敗後重試只會補完其餘，不會重複追加。回傳客戶的清單：每個案件一項產品，附建議 ID。",
    clientListRecorded: "已記錄並起草；客戶的清單",
    clientListNoProduct: "目前還沒有已核實的產品：分析員須先完成審核（包括讀取產品資料），才能檢查客戶",
    clientCases: "保存客戶答案的案件",
    clientQueue: "顧問的客戶待辦清單",
    clientQueueDesc: "唯讀。列出所有有效建議的客戶，最早回答者在前：是否屬易受傷害客戶，以及各案件的結論與決定（等待顧問時為 null）。",
    clientQueueOk: "有效建議的客戶（沒有時為空）",
    clientCasesDesc: "客戶清單的讀取來源：含有此化名 ID 之 client.profiled 的案件 ID。",
    clientCasesOk: "案件 ID（客戶不存在時為空）",
    decideList: "核准或退回客戶的整份清單",
    decideListDesc:
      "對客戶所有仍有效的建議，一次追加 advice.decided，記錄為顧問所做。退回必須附上理由。" +
      "pick_case_id 只能在核准時使用，將一個適合的產品標為顧問的推薦；客戶之後會看到它標示為「Recommended」。" +
      "以 event_id 確保冪等：每一筆事件的 ID 都由它與案件推導而來。",
    decideListOk: "已決定；涵蓋的產品",
    decideListRefused: "沒有仍有效的建議可決定、退回時指定了推薦、推薦的案件不在客戶清單上，或規則不認為適合的產品被指定為推薦",
    payload: "單一事件的完整內容，包含大型欄位",
    payloadOk: "完整內容",
    noEvent: "找不到此事件",
    verify: "重新計算案件的雜湊鏈",
    verifyOk: "驗證結果與最新雜湊值",
  },
} satisfies Record<Lang, Record<string, string>>;

const schemas = {
  OpenCaseRequest,
  OpenCaseResponse,
  IngestDocumentRequest,
  AppendResponse,
  EventPage,
  EventPayloadResponse,
  VerifyResponse,
  RunStepRequest,
  StepResult,
  StepFailure,
  ChangeDispositionRequest,
  CardOperationRequest,
  CardOperationResponse,
  RecordProfileRequest,
  RecordReadingRequest,
  DraftAdviceRequest,
  DecideAdviceRequest,
  RecordClientListRequest,
  ClientListResponse,
  ClientCasesResponse,
  ClientQueueResponse,
  DecideListRequest,
  ErrorResponse,
};

// OpenAPI 3.1 takes JSON Schema 2020-12 as is, minus the $schema marker.
function component(schema: z.ZodType) {
  const json: Record<string, unknown> = z.toJSONSchema(schema, { unrepresentable: "any" });
  delete json.$schema;
  return json;
}

const components = { schemas: Object.fromEntries(Object.entries(schemas).map(([name, s]) => [name, component(s)])) };

function openapi(lang: Lang) {
  const t = TEXT[lang];
  const ref = (name: keyof typeof schemas) => ({ $ref: `#/components/schemas/${name}` });
  const body = (name: keyof typeof schemas) => ({ required: true, content: { "application/json": { schema: ref(name) } } });
  const json = (name: keyof typeof schemas, description: string) => ({
    description,
    content: { "application/json": { schema: ref(name) } },
  });
  const error = (description: string) => json("ErrorResponse", description);
  const caseId = { name: "caseId", in: "path", required: true, schema: { type: "string" } };
  const clientId = { name: "clientId", in: "path", required: true, schema: { type: "string" } };

  return {
    openapi: "3.1.0",
    info: { title: t.title, version: "1.0.0", description: t.description },
    servers: [{ url: origin }],
    paths: {
      "/health": {
        get: { summary: t.health, responses: { 200: { description: t.healthOk } } },
      },
      "/cases": {
        post: {
          summary: t.openCase,
          description: t.openCaseDesc,
          requestBody: body("OpenCaseRequest"),
          responses: { 201: json("OpenCaseResponse", t.opened), 400: error(t.invalidBody) },
        },
      },
      "/cases/{caseId}/documents": {
        post: {
          summary: t.ingest,
          description: t.ingestDesc,
          parameters: [caseId],
          requestBody: body("IngestDocumentRequest"),
          responses: {
            201: json("AppendResponse", t.ingested),
            400: error(t.ingestInvalid),
            404: error(t.unknownCase),
          },
        },
      },
      "/cases/{caseId}/steps": {
        post: {
          summary: t.step,
          description: t.stepDesc,
          parameters: [
            caseId,
            { name: API_TOKEN_HEADER, in: "header", required: false, description: t.apiToken, schema: { type: "string" } },
          ],
          requestBody: body("RunStepRequest"),
          responses: {
            200: json("StepResult", t.stepOk),
            400: error(t.stepInvalid),
            401: error(t.noApiToken),
            404: error(t.unknownCase),
            409: error(t.stepPrecondition),
            422: json("StepFailure", t.stepSchema),
            429: error(t.rateLimited),
            502: json("StepFailure", t.stepUnreachable),
            503: error(t.noModel),
          },
        },
      },
      "/cases/{caseId}/dispositions": {
        post: {
          summary: t.dispose,
          description: t.disposeDesc,
          parameters: [caseId],
          requestBody: body("ChangeDispositionRequest"),
          responses: {
            201: json("AppendResponse", t.disposed),
            400: error(t.disposeInvalid),
            404: error(t.noFinding),
            409: error(t.superseded),
          },
        },
      },
      "/cases/{caseId}/cards": {
        post: {
          summary: t.card,
          description: t.cardDesc,
          parameters: [caseId],
          requestBody: body("CardOperationRequest"),
          responses: {
            201: json("CardOperationResponse", t.cardRecorded),
            400: error(t.cardInvalid),
            404: error(t.unknownCase),
            409: error(t.cardRefused),
          },
        },
      },
      "/cases/{caseId}/clients": {
        post: {
          summary: t.profile,
          description: t.profileDesc,
          parameters: [caseId],
          requestBody: body("RecordProfileRequest"),
          responses: { 201: json("AppendResponse", t.profiled), 400: error(t.profileInvalid), 404: error(t.unknownCase) },
        },
      },
      "/cases/{caseId}/clients/{clientId}/readings": {
        post: {
          summary: t.reading,
          description: t.readingDesc,
          parameters: [caseId, { name: "clientId", in: "path", required: true, schema: { type: "string" } }],
          requestBody: body("RecordReadingRequest"),
          responses: { 201: json("AppendResponse", t.profiled), 400: error(t.invalidBody), 404: error(t.noClient) },
        },
      },
      "/cases/{caseId}/advice": {
        post: {
          summary: t.draftAdvice,
          description: t.draftAdviceDesc,
          parameters: [caseId],
          requestBody: body("DraftAdviceRequest"),
          responses: {
            201: json("AppendResponse", t.drafted),
            400: error(t.invalidBody),
            404: error(t.unknownCase),
            409: error(t.adviceRefused),
          },
        },
      },
      "/cases/{caseId}/advice/{adviceId}/decision": {
        post: {
          summary: t.decideAdvice,
          description: t.decideAdviceDesc,
          parameters: [caseId, { name: "adviceId", in: "path", required: true, schema: { type: "string" } }],
          requestBody: body("DecideAdviceRequest"),
          responses: {
            201: json("AppendResponse", t.disposed),
            400: error(t.invalidBody),
            404: error(t.noAdvice),
            409: error(t.adviceSuperseded),
          },
        },
      },
      "/clients": {
        get: {
          summary: t.clientQueue,
          description: t.clientQueueDesc,
          responses: { 200: json("ClientQueueResponse", t.clientQueueOk) },
        },
        post: {
          summary: t.clientList,
          description: t.clientListDesc,
          requestBody: body("RecordClientListRequest"),
          responses: { 201: json("ClientListResponse", t.clientListRecorded), 400: error(t.invalidBody), 409: error(t.clientListNoProduct) },
        },
      },
      "/clients/{clientId}": {
        get: {
          summary: t.clientCases,
          description: t.clientCasesDesc,
          parameters: [clientId],
          responses: { 200: json("ClientCasesResponse", t.clientCasesOk) },
        },
      },
      "/clients/{clientId}/decision": {
        post: {
          summary: t.decideList,
          description: t.decideListDesc,
          parameters: [clientId],
          requestBody: body("DecideListRequest"),
          responses: {
            201: json("ClientListResponse", t.decideListOk),
            400: error(t.invalidBody),
            409: error(t.decideListRefused),
          },
        },
      },
      "/cases/{caseId}/events": {
        get: {
          summary: t.events,
          parameters: [
            caseId,
            { name: "after", in: "query", schema: { type: "integer", minimum: 0, default: 0 } },
            { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: EVENT_PAGE_LIMIT } },
          ],
          responses: { 200: json("EventPage", t.eventsOk), 404: error(t.unknownCase) },
        },
      },
      "/cases/{caseId}/events/{seq}/payload": {
        get: {
          summary: t.payload,
          parameters: [caseId, { name: "seq", in: "path", required: true, schema: { type: "integer", minimum: 1 } }],
          responses: { 200: json("EventPayloadResponse", t.payloadOk), 404: error(t.noEvent) },
        },
      },
      "/cases/{caseId}/verify": {
        get: {
          summary: t.verify,
          parameters: [caseId],
          responses: { 200: json("VerifyResponse", t.verifyOk), 404: error(t.unknownCase) },
        },
      },
    },
    components,
  };
}

// The switch remembers the choice in localStorage (falling back silently where storage is blocked) and keeps
// it in the URL, so a link opens in the same language.
const page = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Qryvox API</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css">
  <style>
    body { margin: 0; background: #fff; }
    .lang { display: flex; justify-content: flex-end; gap: 4px; padding: 12px 20px 0; font-family: system-ui, sans-serif; }
    .lang button { border: 1px solid #c4c4c4; background: #fff; color: #3b4151; border-radius: 4px; padding: 6px 12px; font-size: 14px; cursor: pointer; }
    .lang button[aria-pressed="true"] { background: #3b4151; border-color: #3b4151; color: #fff; }
  </style>
</head>
<body>
  <nav class="lang" aria-label="Language">
    <button type="button" data-lang="en">English</button>
    <button type="button" data-lang="zh-Hant">繁體中文</button>
  </nav>
  <div id="ui"></div>
  <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    const LANGS = ${JSON.stringify(LANGS)};
    function stored() { try { return localStorage.getItem("qryvox-docs-lang"); } catch { return null; } }
    function remember(lang) { try { localStorage.setItem("qryvox-docs-lang", lang); } catch {} }
    function show(lang) {
      document.documentElement.lang = lang;
      for (const b of document.querySelectorAll(".lang button")) b.setAttribute("aria-pressed", String(b.dataset.lang === lang));
      const url = new URL(location.href);
      url.searchParams.set("lang", lang);
      history.replaceState(null, "", url);
      remember(lang);
      document.getElementById("ui").replaceChildren();
      SwaggerUIBundle({ url: "/openapi.json?lang=" + lang, dom_id: "#ui" });
    }
    for (const b of document.querySelectorAll(".lang button")) b.addEventListener("click", () => show(b.dataset.lang));
    const wanted = new URLSearchParams(location.search).get("lang") || stored();
    show(LANGS.includes(wanted) ? wanted : "en");
  </script>
</body>
</html>`;

const database = openDatabase(env.databaseUrl, env.databaseAuthToken);
await runMigrations(database.db);
await assertAppendOnly(database.client);
const llm = env.llm ? createLlm(env.llm) : null;
// The explorer's own origin is allowed here only; the deployed backend's allow-list is unchanged.
const api = createApp({ ...database, llm, guards: { ...env.guards, allowedOrigins: [...env.guards.allowedOrigins, origin] } });

const explorer = new Hono();
explorer.get("/docs", (c) => c.html(page));
explorer.get("/openapi.json", (c) => {
  const lang = c.req.query("lang");
  return c.json(openapi(LANGS.includes(lang as Lang) ? (lang as Lang) : "en"));
});
explorer.route("/", api);

serve({ fetch: explorer.fetch, port }, () => {
  console.log(`API explorer: ${origin}/docs (${env.databaseUrl})`);
  console.log(llm ? `model: ${llm.model} at ${env.llm?.baseUrl}` : "model: not configured (LLM_BASE_URL / LLM_MODEL)");
});
