// pnpm --filter @qryvox/backend api:docs — local API explorer: Swagger UI at http://localhost:8788/docs over the
// real backend (same database, model and guards as `pnpm dev`, read from ../.env). A development tool only:
// nothing deployed imports it, so production never serves /docs.
//
// The OpenAPI document is generated from the request/response schemas in @qryvox/shared, so it cannot drift
// from the contract. A new endpoint must be added to `paths` below by hand.
import { serve } from "@hono/node-server";
import {
  AppendResponse,
  ErrorResponse,
  EVENT_PAGE_LIMIT,
  EventPage,
  EventPayloadResponse,
  IngestDocumentRequest,
  OpenCaseRequest,
  OpenCaseResponse,
  RunStepRequest,
  StepFailure,
  StepResult,
  VerifyResponse,
} from "@qryvox/shared";
import { Hono } from "hono";
import { z } from "zod";
import { createApp } from "../src/app";
import { assertAppendOnly } from "../src/db/append-only";
import { openDatabase, runMigrations } from "../src/db/client";
import { env } from "../src/env";
import { createLlm } from "../src/llm";

const port = Number(process.env.DOCS_PORT ?? 8788);
const origin = `http://localhost:${port}`;

const schemas = {
  OpenCaseRequest,
  OpenCaseResponse,
  IngestDocumentRequest,
  AppendResponse,
  EventPage,
  EventPayloadResponse,
  VerifyResponse,
  RunStepRequest,
  StepResult,
  StepFailure,
  ErrorResponse,
};

// OpenAPI 3.1 takes JSON Schema 2020-12 as is, minus the $schema marker.
function component(schema: z.ZodType) {
  const json: Record<string, unknown> = z.toJSONSchema(schema, { unrepresentable: "any" });
  delete json.$schema;
  return json;
}

const ref = (name: keyof typeof schemas) => ({ $ref: `#/components/schemas/${name}` });
const json = (name: keyof typeof schemas, description: string) => ({
  description,
  content: { "application/json": { schema: ref(name) } },
});
const error = (description: string) => json("ErrorResponse", description);
const caseId = { name: "caseId", in: "path", required: true, schema: { type: "string" } };

const openapi = {
  openapi: "3.1.0",
  info: {
    title: "Qryvox backend",
    version: "stage-1",
    description:
      "Append-only, hash-chained event log and the four analysis steps. Requests and responses are the zod " +
      "contracts in @qryvox/shared. event_id and step_run_id are generated by the caller, so a retry reuses them.",
  },
  servers: [{ url: origin }],
  paths: {
    "/health": {
      get: {
        summary: "Health, with the shared event vocabulary",
        responses: { 200: { description: "Up; eventTypes proves @qryvox/shared resolved" } },
      },
    },
    "/cases": {
      post: {
        summary: "Open a case",
        description: "Appends one case.opened. The case id is the event_id; a retry returns the same case.",
        requestBody: { required: true, content: { "application/json": { schema: ref("OpenCaseRequest") } } },
        responses: { 201: json("OpenCaseResponse", "Opened"), 400: error("Invalid body") },
      },
    },
    "/cases/{caseId}/documents": {
      post: {
        summary: "Ingest a document",
        description: "Appends document.ingested with the per-page text extracted by pdf.js. Idempotent by event_id.",
        parameters: [caseId],
        requestBody: { required: true, content: { "application/json": { schema: ref("IngestDocumentRequest") } } },
        responses: {
          201: json("AppendResponse", "Ingested"),
          400: error("Invalid body, or page_count differs from the pages sent"),
          404: error("Unknown case"),
        },
      },
    },
    "/cases/{caseId}/steps": {
      post: {
        summary: "Run one analysis step",
        description:
          "extract (input_run_id null) → decompose → contradictions → findings, each consuming the previous " +
          "completed run. A completed step_run_id returns its stored result without calling the model.",
        parameters: [caseId],
        requestBody: { required: true, content: { "application/json": { schema: ref("RunStepRequest") } } },
        responses: {
          200: json("StepResult", "Completed, now or earlier"),
          404: error("Unknown case"),
          409: error("Cannot run yet: no documents, or input_run_id is not a completed run of the previous step"),
          422: json("StepFailure", "Model output failed its schema or grounding; step.failed appended"),
          429: error("Rate limited; see Retry-After"),
          502: json("StepFailure", "Model unreachable; step.failed appended"),
          503: error("No model configured"),
        },
      },
    },
    "/cases/{caseId}/events": {
      get: {
        summary: "List events (slim), paged by seq",
        parameters: [
          caseId,
          { name: "after", in: "query", schema: { type: "integer", minimum: 0, default: 0 } },
          { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: EVENT_PAGE_LIMIT } },
        ],
        responses: { 200: json("EventPage", "Events with seq > after"), 404: error("Unknown case") },
      },
    },
    "/cases/{caseId}/events/{seq}/payload": {
      get: {
        summary: "One event's full payload, heavy fields included",
        parameters: [caseId, { name: "seq", in: "path", required: true, schema: { type: "integer", minimum: 1 } }],
        responses: { 200: json("EventPayloadResponse", "Full payload"), 404: error("No such event") },
      },
    },
    "/cases/{caseId}/verify": {
      get: {
        summary: "Re-hash the case's chain",
        responses: { 200: json("VerifyResponse", "Verdict and latest hash"), 404: error("Unknown case") },
        parameters: [caseId],
      },
    },
  },
  components: { schemas: Object.fromEntries(Object.entries(schemas).map(([name, s]) => [name, component(s)])) },
};

const page = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Qryvox API</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css">
</head>
<body>
  <div id="ui"></div>
  <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>SwaggerUIBundle({ url: "/openapi.json", dom_id: "#ui" });</script>
</body>
</html>`;

const database = openDatabase(env.databaseUrl, env.databaseAuthToken);
await runMigrations(database.db);
await assertAppendOnly(database.client);
const llm = env.llm ? createLlm(env.llm) : null;
// The explorer's own origin is allowed here only; the deployed backend's allow-list is unchanged.
const api = createApp({ ...database, llm, guards: { ...env.guards, allowedOrigins: [...env.guards.allowedOrigins, origin] } });

const explorer = new Hono();
explorer.get("/docs", (c) => c.html(page));
explorer.get("/openapi.json", (c) => c.json(openapi));
explorer.route("/", api);

serve({ fetch: explorer.fetch, port }, () => {
  console.log(`API explorer: ${origin}/docs (${env.databaseUrl})`);
  console.log(llm ? `model: ${llm.model} at ${env.llm?.baseUrl}` : "model: not configured (LLM_BASE_URL / LLM_MODEL)");
});
