import { z } from "zod";
import { CardId } from "./card.js";
import {
  CardDiscarded,
  CardDocked,
  CardEvent,
  CardPinned,
  CardRestored,
  CardSimilarRequested,
  CardUndocked,
  CardUnpinned,
  IngestedDocument,
  Sha256,
  SlimEvent,
  StepName,
} from "./events.js";
import { AdviceDecision, DecisionConfirmation, RejectionReason } from "./advice.js";
import { ClientProfile, KnowledgeLevel } from "./client.js";
import { Citation, Disposition } from "./finding.js";
import { ParseInput } from "./intent.js";

// event_id is generated by the browser so that a retry after a network failure reuses it (ADR-0002).
// A case is named after the event that opens it: case_id = the case.opened event_id.

export const OpenCaseRequest = z.object({ event_id: z.uuid() });
export type OpenCaseRequest = z.infer<typeof OpenCaseRequest>;

export const OpenCaseResponse = z.object({ case_id: z.string(), seq: z.number().int() });
export type OpenCaseResponse = z.infer<typeof OpenCaseResponse>;

export const IngestDocumentRequest = z.object({ event_id: z.uuid(), document: IngestedDocument });
export type IngestDocumentRequest = z.infer<typeof IngestDocumentRequest>;

export const AppendResponse = z.object({ seq: z.number().int() });
export type AppendResponse = z.infer<typeof AppendResponse>;

// POST /cases/:caseId/dispositions — the analyst's explicit decision on one finding. event_id is the
// browser's, so a retry after a network failure appends nothing (ADR-0002). There is no un-disposition:
// the contract admits approve and dismiss and nothing else, because nothing transitions out of either
// state but a further decision by the analyst (spec decision 34).
export const ChangeDispositionRequest = z.object({
  event_id: z.uuid(),
  finding_id: z.string().min(1),
  disposition: Disposition,
});
export type ChangeDispositionRequest = z.infer<typeof ChangeDispositionRequest>;

// --- The client layer (stage 2, #31). event_id is the browser's, so a retry appends nothing. ---

// POST /cases/:caseId/clients — a new version of a client's profile. Advice drafted on the previous
// version is superseded in the same transaction.
// by_client: the client gave these answers themselves, on their own page, rather than an adviser
// recording them; the event's actor is then the client's pseudonymous id.
export const RecordProfileRequest = z.object({ event_id: z.uuid(), profile: ClientProfile, by_client: z.boolean().optional() });
export type RecordProfileRequest = z.infer<typeof RecordProfileRequest>;

// POST /cases/:caseId/clients/:clientId/readings — the depth a client chose, shared by them (#38).
export const RecordReadingRequest = z.object({ event_id: z.uuid(), advice_id: z.uuid(), depth: KnowledgeLevel });
export type RecordReadingRequest = z.infer<typeof RecordReadingRequest>;

// POST /cases/:caseId/advice — draft advice for a client from their latest profile and the latest
// completed attributes run. The advice's id is this event_id.
export const DraftAdviceRequest = z.object({ event_id: z.uuid(), client_id: z.string().min(1) });
export type DraftAdviceRequest = z.infer<typeof DraftAdviceRequest>;

// POST /cases/:caseId/advice/:adviceId/decision — the adviser approves or rejects.
export const DecideAdviceRequest = z.object({
  event_id: z.uuid(),
  decision: AdviceDecision,
  reason: RejectionReason.optional(),
  confirmations: z.array(DecisionConfirmation).optional(),
  // #71: mark this approved, suitable product as the adviser's pick. Refused on anything else.
  adviser_pick: z.boolean().optional(),
});
export type DecideAdviceRequest = z.infer<typeof DecideAdviceRequest>;

// --- The client's list (#71, ADR-0008): one questionnaire, every verified product. ---

// POST /clients — a client's answers, given once on /start, recorded as a client.profiled in every verified
// product's case and drafted against each. event_id is the browser's: every event the call appends takes an
// id derived from it and the case, so a retry after a partial failure finishes the rest and appends nothing twice.
export const RecordClientListRequest = z.object({ event_id: z.uuid(), profile: ClientProfile });
export type RecordClientListRequest = z.infer<typeof RecordClientListRequest>;

// One product of a client's list: the case it was verified in, and the advice drafted there for the client.
export const ClientListProduct = z.object({ case_id: z.string().min(1), advice_id: z.uuid() });
export type ClientListProduct = z.infer<typeof ClientListProduct>;
export const ClientListResponse = z.object({ client_id: z.string().min(1), products: z.array(ClientListProduct) });
export type ClientListResponse = z.infer<typeof ClientListResponse>;

// GET /clients/:clientId — the cases that hold this client's answers: where the list's products are read from.
export const ClientCasesResponse = z.object({ client_id: z.string().min(1), case_ids: z.array(z.string().min(1)) });
export type ClientCasesResponse = z.infer<typeof ClientCasesResponse>;

// POST /clients/:clientId/decision — the adviser decides the client's whole list in one decision: every
// advice of theirs in play is approved (or rejected, with the one reason). pick_case_id marks one suitable
// product as the adviser's pick, on approval only.
export const DecideListRequest = z.object({
  event_id: z.uuid(),
  decision: AdviceDecision,
  reason: RejectionReason.optional(),
  confirmations: z.array(DecisionConfirmation).optional(),
  pick_case_id: z.string().min(1).optional(),
});
export type DecideListRequest = z.infer<typeof DecideListRequest>;

// The judge-link token (ADR-0001): the demo URL carries ?k=<token>, the browser keeps it in sessionStorage
// and sends it in this header on every POST /cases/:caseId/steps. A backend with JUDGE_TOKEN set refuses an
// analysis step without the matching token (401); nothing else needs it, so the board and replay stay open.
export const JUDGE_TOKEN_PARAM = "k";
export const JUDGE_TOKEN_HEADER = "x-judge-token";

export const EVENT_PAGE_LIMIT = 200;

// GET /cases/:caseId/events?after=N — events with seq > N, oldest first.
export const EventPage = z.object({ events: z.array(SlimEvent), has_more: z.boolean() });
export type EventPage = z.infer<typeof EventPage>;

// GET /cases/:caseId/events/:seq/payload — the full payload, heavy fields included.
export const EventPayloadResponse = z.object({ seq: z.number().int(), payload: z.record(z.string(), z.unknown()) });
export type EventPayloadResponse = z.infer<typeof EventPayloadResponse>;

// GET /cases/:caseId/verify — server-side re-hash of the whole chain.
export const VerifyResponse = z.object({
  intact: z.boolean(),
  event_count: z.number().int(),
  latest_hash: Sha256.nullable(),
  // First seq whose stored hash or link does not match; null when intact.
  broken_at_seq: z.number().int().nullable(),
});
export type VerifyResponse = z.infer<typeof VerifyResponse>;

export const ErrorResponse = z.object({ error: z.string() });
export type ErrorResponse = z.infer<typeof ErrorResponse>;

// POST /cases/:caseId/steps — run one analysis step. step_run_id is generated by the browser, so a
// retry reuses it: if that run already completed, the stored result comes back without a model call.
export const RunStepRequest = z
  .object({
    step_run_id: z.uuid(),
    step: StepName,
    // The completed run of the previous step to consume; null for the steps that read the documents
    // (extract, attributes) and for parse. For explain, the id of the advice it explains; for rationale, the
    // completed findings run whose findings it words.
    input_run_id: z.string().min(1).nullable(),
    // parse only, and required for it: the analyst's free-text intent (ParseInput).
    intent: ParseInput.shape.intent.optional(),
    // A find-similar re-run (#64), on a seedable step only: the passage to find more like, which must be
    // quoted verbatim from its page. A seeded run's output is candidate cards for the canvas; it never
    // becomes another step's input, so it never reaches the findings on the board.
    seed: Citation.optional(),
  })
  .refine((r) => (r.step === "parse") === (r.intent !== undefined), {
    message: "intent is required for the parse step and only for it",
    path: ["intent"],
  })
  .refine((r) => r.seed === undefined || isSeedable(r.step), {
    message: "only the extract and contradictions steps take a seed",
    path: ["seed"],
  });
export type RunStepRequest = z.infer<typeof RunStepRequest>;

// The steps a seeded re-run may name, on POST /steps and on a card's find similar (#64): the one that reads
// the documents, and the one that looks for claims that disagree. findings itself never takes a seed, since
// it is the only step that writes findings.
export const SEEDABLE_STEPS = ["extract", "contradictions"] as const satisfies readonly StepName[];
export type SeedableStep = (typeof SEEDABLE_STEPS)[number];

export function isSeedable(step: StepName): step is SeedableStep {
  return (SEEDABLE_STEPS as readonly StepName[]).includes(step);
}

// POST /cases/:caseId/cards — one card operation on a live case's canvas (#65): a card event as the
// browser makes it, without the envelope, which the server supplies (the analyst as actor, the next seq).
// event_id is the browser's, so a retry appends nothing. The server answers with the event it appended.
// Find similar names the step it re-runs, which the canvas takes to be FIND_SIMILAR_STEP whatever the card;
// any seedable step is still admitted, since contradictions can be seeded through this endpoint (#64, #66).
export const CardOperationRequest = z.discriminatedUnion("type", [
  CardDocked.pick({ event_id: true, type: true, payload: true }),
  CardUndocked.pick({ event_id: true, type: true, payload: true }),
  CardPinned.pick({ event_id: true, type: true, payload: true }),
  CardUnpinned.pick({ event_id: true, type: true, payload: true }),
  CardDiscarded.pick({ event_id: true, type: true, payload: true }),
  CardRestored.pick({ event_id: true, type: true, payload: true }),
  CardSimilarRequested.pick({ event_id: true, type: true }).extend({
    payload: z.object({ card_id: CardId, step_kind: z.enum(SEEDABLE_STEPS) }),
  }),
]);
export type CardOperationRequest = z.infer<typeof CardOperationRequest>;

// The step find-similar re-runs, whichever card it is pressed from: extract, seeded with the passage the
// card shows (#66). A finding card used to re-run contradictions, which returned the very passage its own
// citation already had a card for, so a press on it found nothing. Contradictions stays seedable through the
// API for a caller that wants it; only the canvas has stopped asking for it.
export const FIND_SIMILAR_STEP = "extract" as const satisfies SeedableStep;

// 201: the card event as appended (or, for a retried event_id, as appended the first time).
export const CardOperationResponse = CardEvent;
export type CardOperationResponse = z.infer<typeof CardOperationResponse>;

// 200: the run completed (now, or earlier — a retry gets the identical body).
export const StepResult = z.object({
  step_run_id: z.string(),
  step: StepName,
  seq: z.number().int(),
  prompt_version: z.string(),
  model: z.string(),
  output: z.record(z.string(), z.unknown()),
});
export type StepResult = z.infer<typeof StepResult>;

// 422 (model output failed its schema) or 502 (model unreachable): step.failed was appended; retrying
// with the same step_run_id runs the model again.
export const StepFailure = z.object({ error: z.string(), step_run_id: z.string(), seq: z.number().int() });
export type StepFailure = z.infer<typeof StepFailure>;
